"""Initial migration

Revision ID: c1a3d1eb0b10
Revises: 
Create Date: 2026-01-26 14:32:03.227823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a3d1eb0b10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Handle Entrepreneurs Table
    # Drop old PK constraint safely using SQL
    op.execute("ALTER TABLE entrepreneurs DROP CONSTRAINT IF EXISTS entrepreneurs_pkey CASCADE")

    # Rename old ID (phone number) to temp
    op.alter_column('entrepreneurs', 'id', new_column_name='old_id_str')
    
    # Add new columns
    # We add 'id' as Integer first, then make it PK later to avoid issues during data copy if needed, 
    # but Serial implies unique/not null.
    op.add_column('entrepreneurs', sa.Column('id', sa.Integer(), sa.Identity(), nullable=False))
    op.add_column('entrepreneurs', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('entrepreneurs', sa.Column('is_active', sa.Boolean(), server_default='true'))
    op.add_column('entrepreneurs', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Copy data: phone_number = old_id_str
    op.execute("UPDATE entrepreneurs SET phone_number = old_id_str")
    
    # Make phone_number index
    op.create_index(op.f('ix_entrepreneurs_phone_number'), 'entrepreneurs', ['phone_number'], unique=False)

    # 2. Handle Messages Table
    # Rename old FK
    op.alter_column('messages', 'entrepreneur_id', new_column_name='old_entrepreneur_id_str')
    
    # Add new FK column
    op.add_column('messages', sa.Column('entrepreneur_id', sa.Integer(), nullable=True))
    
    # Map old string FK to new Integer ID
    op.execute("""
        UPDATE messages 
        SET entrepreneur_id = e.id 
        FROM entrepreneurs e 
        WHERE messages.old_entrepreneur_id_str = e.old_id_str
    """)
    
    # Drop old columns
    op.drop_column('entrepreneurs', 'old_id_str')
    op.drop_column('messages', 'old_entrepreneur_id_str')
    op.execute("ALTER TABLE messages DROP COLUMN IF EXISTS status")
    
    # Create new PK and FK
    op.create_primary_key("entrepreneurs_pkey", "entrepreneurs", ["id"])
    op.create_foreign_key("messages_entrepreneur_id_fkey", "messages", "entrepreneurs", ["entrepreneur_id"], ["id"])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('messages', 'entrepreneur_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_entrepreneurs_phone_number'), table_name='entrepreneurs')
    op.alter_column('entrepreneurs', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('entrepreneurs', 'created_at')
    op.drop_column('entrepreneurs', 'is_active')
    op.drop_column('entrepreneurs', 'phone_number')
    # ### end Alembic commands ###
